### ISSUE TITLE
Using loaderUtils deprecated code

### ISSUE THREAD

**Issue by artemkaint** [AlexanderPavlenko/react-templates-loader#22]
Upgrade dependency to last version of loaderUtils

```(node:1) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
webpack_1       | parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
webpack_1       |     at Object.parseQuery (/opt/project/node_modules/react-templates-loader/node_modules/loader-utils/index.js:78:3)
webpack_1       |     at Object.module.exports (/opt/project/node_modules/react-templates-loader/index.js:7:28)
webpack_1       |     at LOADER_EXECUTION (/opt/project/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
webpack_1       |     at runSyncOrAsync (/opt/project/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
webpack_1       |     at iterateNormalLoaders (/opt/project/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
webpack_1       |     at Array.<anonymous> (/opt/project/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
webpack_1       |     at Storage.finished (/opt/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
webpack_1       |     at /opt/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
webpack_1       |     at /opt/project/node_modules/graceful-fs/graceful-fs.js:78:16
webpack_1       |     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)```

**Comment by AlexanderPavlenko** [comment]
Fixed by https://github.com/AlexanderPavlenko/react-templates-loader/pull/23
